const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  dept:state =>state.user.dept,
  permissions: state => state.user.permissions,
  permission_routes: state => state.permission.routes,
  keyList: state => state.permission.keyList,
  activeKey: state => state.permission.activeKey,
  renderList: state => state.permission.renderList,
  activeRouter:state => state.permission.activeRouter,
  theme:state => state.settings.theme,
}
export default getters
